name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build order-service
      run: |
        cd order-service
        go build -v -o order-service-app ./cmd/order-service

    - name: Build payment-service
      run: |
        cd payment-service
        go build -v -o payment-service-app ./cmd/payment-service

    - name: Test order-service
      run: |
        cd order-service
        go test -v ./...

    - name: Test payment-service
      run: |
        cd payment-service
        go test -v ./...
